version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: pg

    restart: unless-stopped

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${PG_HOST_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  airflow-init:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow_init

    entrypoint: ""
    environment:
      AIRFLOW_UID: 1000
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    depends_on:
      - postgres
    command: >
      sh -c "airflow db init &&
             airflow users create
               --username ${AIRFLOW_USER}
               --password ${AIRFLOW_PASSWORD}
               --firstname Admin
               --lastname User
               --role Admin
               --email ${AIRFLOW_EMAIL}"

  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow_webserver
    
    restart: unless-stopped

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    environment:
      AIRFLOW_UID: 1000
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      AIRFLOW__WEBSERVER__SECRET_KEY: "supersecretkey"

      # –õ–æ–≥–∏ Airflow
      AIRFLOW__CORE__BASE_LOG_FOLDER: /opt/airflow/logs
      AIRFLOW__CORE__DAG_PROCESSOR_MANAGER_LOG_LOCATION: /opt/airflow/logs/dag_processor_manager/dag_processor_manager.log
      AIRFLOW__LOGGING__LOGGING_LEVEL: INFO

      # üîΩ –ù–∞—Å—Ç—Ä–æ–π–∫–∏ –¥–ª—è —Å–ª–∞–±–æ–≥–æ –Ω–æ—É—Ç–±—É–∫–∞
      AIRFLOW__WEBSERVER__WEB_SERVER_WORKERS: 1
      AIRFLOW__WEBSERVER__WEB_SERVER_WORKER_TIMEOUT: 300
      AIRFLOW__WEBSERVER__WEB_SERVER_MASTER_TIMEOUT: 300
      AIRFLOW__WEBSERVER__WEB_SERVER_PRELOAD: "False"

      # MinIO
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BUCKET: ${MINIO_BUCKET}

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 40s


    depends_on:
      - postgres
      - airflow-init
    ports:
      - "${AIRFLOW_PORT}:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./configs:/opt/airflow/configs
      - ./dags/data:/opt/airflow/dags/data
      - ./logs:/opt/airflow/logs
    command: webserver

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow_scheduler
    
    restart: unless-stopped

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    environment:
      AIRFLOW_UID: 1000
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      AIRFLOW__WEBSERVER__SECRET_KEY: "supersecretkey"
      AIRFLOW__CORE__BASE_LOG_FOLDER: /opt/airflow/logs
      AIRFLOW__CORE__DAG_PROCESSOR_MANAGER_LOG_LOCATION: /opt/airflow/logs/dag_processor_manager/dag_processor_manager.log
      AIRFLOW__LOGGING__LOGGING_LEVEL: INFO

      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BUCKET: ${MINIO_BUCKET}

    depends_on:
      - postgres
      - airflow-init
    volumes:
      - ./dags:/opt/airflow/dags
      - ./configs:/opt/airflow/configs
      - ./dags/data:/opt/airflow/dags/data
      - ./logs:/opt/airflow/logs
    command: scheduler

  minio:
    image: minio/minio
    container_name: minio
    
    restart: unless-stopped

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s

    ports:
      - "9000:9000"   # –¥–æ—Å—Ç—É–ø –∫ S3 API
      - "9001:9001"   # –¥–æ—Å—Ç—É–ø –∫ –≤–µ–±-–∫–æ–Ω—Å–æ–ª–∏
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - ./minio_data:/data

  adminer:
    image: adminer
      
    restart: unless-stopped

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        
    ports:
      - "${ADMINER_HOST_PORT}:8080"
    depends_on:
      - postgres

volumes:
  pg_data:
  minio_data:

